# Generated by Django 3.1.7 on 2022-01-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiOferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MiProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('img', models.CharField(max_length=530)),
            ],
        ),
    ]
